apiVersion: v1
kind: Service
metadata:
  name: {{ include "mocache.fullname" . }}-headless
  labels:
    {{- include "mocache.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: false
  selector:
    {{- include "mocache.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: http
    - name: grpc
      port: {{ .Values.ports.rpc }}
      targetPort: grpc
    {{- if .Values.resp.enabled }}
    - name: resp
      port: {{ .Values.ports.resp }}
      targetPort: resp
    {{- end }}
    {{- if and .Values.resp.enabled .Values.resp.cluster.enabled .Values.resp.cluster.bus }}
    - name: bus
      port: {{ add (int .Values.ports.resp) 10000 }}
      targetPort: bus
    {{- end }}
